"""empty message

Revision ID: 777b0071e704
Revises: 199023ec1322
Create Date: 2022-02-28 22:04:56.188818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777b0071e704'
down_revision = '199023ec1322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share', 'create_time')
    # ### end Alembic commands ###
